version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8082:8082
    image: app:django
    container_name: insta_container
    command: python manage.py runserver 0.0.0.0:8082
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_insta_db
