# Generated by Django 4.2.5 on 2023-10-06 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaprojects', '0004_alter_like_id_alter_like_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='liked',
        ),
    ]
